export const techStack = [
    "HTML",
    "CSS",
    "JavaScript",
    "React.js",
    "Angular",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Bootstrap",
    "Tailwind CSS",
    "Material-UI",
    "Node.js",
    "Express.js",
    "NestJS",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Laravel",
    "Ruby on Rails",
    "ASP.NET Core",
    "Go",
    "Rust",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "SQL Server",
    "MongoDB",
    "CouchDB",
    "Cassandra",
    "Firestore",
    "Redis",
    "Memcached",
    "Redshift",
    "BigQuery",
    "Snowflake",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "GraphQL",
    "gRPC",
    "RabbitMQ",
    "Apache Kafka",
    "Swift",
    "Kotlin",
    "React Native",
    "Flutter",
    "Jest",
    "Cypress",
    "Selenium",
    "Playwright",
    "TensorFlow",
    "PyTorch",
    "Pandas",
    "NumPy",
    "Tableau",
    "Power BI",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Prometheus",
    "Grafana",
    "Sentry",
    "ELK Stack",
    "Datadog",
  ];
  