apiVersion: apps/v1
kind: Deployment
metadata:
 name: chat-depl
spec:
 replicas: 1
 selector:
   matchLabels:
     app: chat
 template:
   metadata:
     labels:
       app: chat
   spec:
     containers:
       - name: chat
         image: najinn675943/prosphere_chat_service
         env:
           - name: MONGO_URL
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: MONGO_URL
           - name: PORT
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: CHAT_PORT
           - name: MESSAGE_BROKERS
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: MESSAGE_BROKERS
           - name: PROD_FRONTEND_DOMAIN
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: PROD_FRONTEND_DOMAIN      
         ports:
           - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: chat-srv
spec:
 type: ClusterIP
 selector:
   app: chat
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080