apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: najinn675943/prosphere_client_service
          env:
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GATEWAY_URL
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_URL
            - name: PROFILE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PROFILE_URL
            - name: COMPANY_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: COMPANY_URL
            - name: USER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_URL
            - name: VITE_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_STRIPE_PUBLISHABLE_KEY
            
          ports:
            - containerPort: 1573

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 1573
      targetPort: 1573