apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: najinn675943/prosphere_company_service
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: MESSAGE_BROKERS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MESSAGE_BROKERS
            - name: GRPC_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GRPC_PORT
            - name: PROTO_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PROTO_URL
            - name: COMPANY_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: COMPANY_ACCESS_SECRET
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BUCKET_NAME
            - name: BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BUCKET_REGION
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ACCESS_KEY
            - name: PROD_FRONTEND_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PROD_FRONTEND_DOMAIN
            - name: port
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: COMPANY_PORT
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: company-srv
spec:
  type: ClusterIP
  selector:
    app: company
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003