apiVersion: apps/v1
kind: Deployment
metadata:
 name: job-depl
spec:
 replicas: 1
 selector:
   matchLabels:
     app: job
 template:
   metadata:
     labels:
       app: job
   spec:
     containers:
       - name: job
         image: najinn675943/prosphere_job_service
         env:
           - name: MONGO_URL
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: MONGO_URL
           - name: MESSAGE_BROKERS
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: MESSAGE_BROKERS
           - name: COMPANY_ACCESS_SECRET
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: COMPANY_ACCESS_SECRET
           - name: PORT
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: JOB_PORT
           - name: PROD_FRONTEND_DOMAIN
             valueFrom:
               secretKeyRef:
                 name: app-secrets
                 key: PROD_FRONTEND_DOMAIN      
  
         ports:
           - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
 name: job-srv
spec:
 type: ClusterIP
 selector:
   app: job
 ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000