export enum ErrorCodes {
    RESET_REQUEST_IN_PROGRESS = "RESET_REQUEST_IN_PROGRESS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    INVALID_TOKEN = "INVALID_TOKEN",
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK",
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
    FORBIDDEN_ACTION = "FORBIDDEN_ACTION",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
}

export enum CompanyType {
  STARTUP = "Startup",
  PUBLIC = "Public Company",
  PRIVATE = "Private Company",
  NON_PROFIT = "Non-Profit",
  GOVERNMENT = "Government",
  EDUCATIONAL = "Educational Institution",
  SELF_EMPLOYED = "Self-Employed",
  PARTNERSHIP = "Partnership"
}