
export enum TeamRole {
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  MEMBER = "MEMBER",
  GUEST = "GUEST",
}


export enum CompanyStatus {
  PENDING = "PENDING",
  REJECTED = "REJECTED",
  ACTIVE = "ACTIVE",
  UNDER_REVIEW = "UNDER_REVIEW",
  SUSPENDED = "SUSPENDED",
  INACTIVE = "INACTIVE",
  VERIFIED = "VERIFIED",
}

export enum ErrorCode {
   COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
   NO_COMPANIES_FOUND = 'NO_COMPANIES_FOUND',
   USER_ALREADY_EXISIT = 'USER_ALREADY_EXISIT',
   COMPANY_ALREADY_EXISTS = 'COMPANY_ALREADY_EXISTS',
   FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
   INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
   FILE_SIZE_EXCEEDED = 'FILE_SIZE_EXCEEDED'
} 

export enum TokenType {
   COMPANY_ACCESS_TOKEN = "companyAccess",
}